name: Build Docker

on:
  push:
   branches: [ master ]
  pull_request:
    branches: [ master ]
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build & Push Image
      run: |
        echo "${{ secrets.DOCKERPW }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
        docker image build -t "${{ secrets.DOCKER_HUB_USERNAME }}"/anasty:latest .
        docker push "${{ secrets.DOCKER_HUB_USERNAME }}"/anasty:latest
